---
- name: install ovenmedian
  hosts: edge
  tasks:
    - name: edge
      shell: |
        systemctl stop ovenmediaengine
 
- name: install ovenmedian
  hosts: pulledge
  tasks:
    - name: edge
      shell: |
        systemctl stop ovenmediaengine
        
