---
- name: Shell mkdir
  hosts: 103.113.83.245
  tasks:
    - name: mkdir 11
      shell: mkdir /usr/local/src/testdemo01

- name: Update 
  hosts: 103.113.83.244
  tasks:
    - name: mkdir 12
    shell: mkdir /usr/local/src/testdemo02
