---
- name: install ovenmedian
  hosts: edge
  tasks:
    - name: edge
      shell: |
        ping 8.8.8.8 -c 5
 
- name: install ovenmedian
  hosts: pulledge
  tasks:
    - name: edge
      shell: |
        ping 8.8.8.8 -c 5
        
