---
- name: Shell mkdir
  hosts: edge
  tasks:
    - name: mkdir 11
      shell: |
        sudo systemctl stop firewalld
        sudo systemctl disable firewalld
        sudo systemctl mask --now firewalld
        sudo yum install iptables-services
